set -u __fish_initialized 3400
set -u fish_color_autosuggestion 969896
set -u fish_color_cancel \x2d\x2dreverse
set -u fish_color_command b294bb
set -u fish_color_comment f0c674
set -u fish_color_cwd green
set -u fish_color_cwd_root red
set -u fish_color_end b294bb
set -u fish_color_error cc6666
set -u fish_color_escape 00a6b2
set -u fish_color_history_current \x2d\x2dbold
set -u fish_color_host normal
set -u fish_color_host_remote \x1d
set -u fish_color_keyword \x1d
set -u fish_color_match \x2d\x2dbackground\x3dbrblue
set -u fish_color_normal normal
set -u fish_color_operator 00a6b2
set -u fish_color_option \x1d
set -u fish_color_param 81a2be
set -u fish_color_quote b5bd68
set -u fish_color_redirection 8abeb7
set -u fish_color_search_match bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -u fish_color_selection white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -u fish_color_status red
set -u fish_color_user brgreen
set -u fish_color_valid_path \x2d\x2dunderline
set -u fish_key_bindings fish_vi_key_bindings
set -u fish_pager_color_background \x1d
set -u fish_pager_color_completion normal
set -u fish_pager_color_description B3A06D
set -u fish_pager_color_prefix normal\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -u fish_pager_color_progress brwhite\x1e\x2d\x2dbackground\x3dcyan
set -u fish_pager_color_secondary_background \x1d
set -u fish_pager_color_secondary_completion \x1d
set -u fish_pager_color_secondary_description \x1d
set -u fish_pager_color_secondary_prefix \x1d
set -u fish_pager_color_selected_background \x2d\x2dbackground\x3dbrblack
set -u fish_pager_color_selected_completion \x1d
set -u fish_pager_color_selected_description \x1d
set -u fish_pager_color_selected_prefix \x1d

