#!/usr/bin/env bash

darkgreen="$(xrdb -query  | grep 'i3.color11:' | cut -f 2)"
lightgreen="$(xrdb -query | grep 'i3.color3:'  | cut -f 2)"
yellow="$(xrdb -query     | grep 'i3.color2:'  | cut -f 2)"
salmon="$(xrdb -query     | grep 'i3.color1:'  | cut -f 2)"
pink="$(xrdb -query       | grep 'i3.color6:'  | cut -f 2)"


blue="$(xrdb -query | grep "i3.color4" | cut -f 2)"
darkblue="$(xrdb -query | grep "i3.color12" | cut -f 2)"
purple="$(xrdb -query | grep "i3.color5" | cut -f 2)"
white="$(xrdb -query | grep "i3.background" | cut -f 2)"
darkgray="$(xrdb -query | grep "i3.color8" | cut -f 2)"


readarray -t output <<< $(acpi battery)
battery_count=${#output[@]}

for line in "${output[@]}";
do
    percentages+=($(echo "$line" | grep -o -m1 '[0-9]\{1,3\}%' | tr -d '%'))
    statuses+=($(echo "$line" | egrep -o -m1 'Discharging|Charging|AC|Full|Unknown'))
    remaining=$(echo "$line" | egrep -o -m1 '[0-9][0-9]:[0-9][0-9]')
    if [[ -n $remaining ]]; then
        remainings+=(" ($remaining)")
    else 
        remainings+=("")
    fi
done


charging_color="$blue"
full_color="$white"
ac_color="$purple"

dis_colors=("$pink" "$salmon" "$yellow" "$lightgreen" "$darkgreen")
bg_color="$darkgray"



end=$(($battery_count - 1))
for i in $(seq 0 $end);
do
    case "${statuses[$i]}" in
    "Charging")
        color="$white"
        bg_color="$charging_color"
    ;;
    "Full")
        color="$full_color"
    ;;
    "AC")
        bg_color="$ac_color"
        color="$white"
    ;;
    "Discharging"|"Unknown")

        if (( percentages[$i] >= 0 && percentages[$i] < 20 )); then
          color="${dis_colors[0]}"
        elif (( percentages[$i] >= 20 && percentages[$i] < 40 )); then
          color="${dis_colors[1]}"
        elif (( percentages[$i] >= 40 && percentages[$i] < 60 )); then
          color="${dis_colors[2]}"
        elif (( percentages[$i] >= 60 && percentages[$i] < 80 )); then
          color="${dis_colors[3]}"
        elif (( percentages[$i] >= 80 && percentages[$i] <= 100 )); then
          color="${dis_colors[4]}"
        fi
    
    ;;
    *) 
      color="$ac_color"
      esac

    if (( $end > 0 )) ; then 
        message="$message $(($i + 1)):" 
    fi
    
    if [[ -z bg_color ]] ; then
      message="$message <span foreground=\"$color\">${percentages[$i]}%</span>" 
    else
      message="$message <span foreground=\"$color\" background=\"$bg_color\">${percentages[$i]}%</span>" 
    fi
    echo $message
done
