#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;
use Switch;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

#colors
my @dis_colors = ("#FF0027", "#FF3B05", "#FFB923", "#FFD000", "#E4FF00", "#ADFF00", "#6DFF00", "#10BA00");
my $charging_color = "#00AFE3";
my $full_color = "#FFFFFF";
my $ac_color = "#535353";

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

if ($status eq 'Discharging') {
	$full_text .= '🔋🗲';
} elsif ($status eq 'Charging') {
	$full_text .= ' 🔋🔌';
} elsif ($status eq 'AC') {
  $full_text .= '🔌🗲';
} elsif ($status eq 'Full'){
  $full_text .= '🔋✔';
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# color and urgent flag
  switch ($status) {
    case 'Discharging'{
      if ($percent >= 0 && $percent < 10) {
        print $dis_colors[0];
      }elsif ($percent >=10 && $percent < 20) {
        print $dis_colors[1];
      }elsif ($percent >=20 && $percent < 30) {
        print $dis_colors[2];
      }elsif ($percent >=30 && $percent < 40) {
        print $dis_colors[3];
      }elsif ($percent >=40 && $percent < 50) {
        print $dis_colors[4];
      }elsif ($percent >=50 && $percent < 65) {
        print $dis_colors[5];
      }elsif ($percent >=65 && $percent < 80) {
        print $dis_colors[6];
      }elsif ($percent >=80) {
        print $dis_colors[7];
    }
    }
    case 'Charging'{
      print $charging_color;
    }
    case 'AC'{
      print $ac_color;
    }
    case 'Full'{
      print $full_color;
    }
    print "\n";

	}
	

	if ($percent < 5) {
		exit(33);
	}

exit(0);
