#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;
use Getopt::Long;

# default values
my $t_warn = 60;
my $t_crit = 80;
my $cpu_temp = -1;
my $filename = "/sys/class/thermal/thermal_zone1/temp";

sub help {
    print "Usage: cpu_temp [-w <warning>] [-c <critical>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit);

# Get CPU temp
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (my $fh, '<', $filename) or die;
$cpu_temp = <fh>;

$cpu_temp eq -1 and die 'Can\'t read temp information';

# Print short_text, full_text
printf "%02.2f%%\n", $cpu_temp;
printf "%02.2f%%\n", $cpu_temp;

# Print color, if needed
if ($cpu_temp >= $t_crit) {
    print "#FF0000\n";
    exit 33;
} elsif ($cpu_temp >= $t_warn) {
    print "#FFFC00\n";
}

exit 0;
